import member1 from '../../Images/team-1.png'
import member2 from '../../Images/team-2.png'
import member3 from '../../Images/team-3.png'
import member4 from '../../Images/team-4.png'
import member5 from '../../Images/team-5.png'
import member6 from '../../Images/team-6.png'
import client1 from '../../Images/clients-logo-01.png'
import client2 from '../../Images/clients-logo-02.png'
import client3 from '../../Images/clients-logo-03.png'
import client4 from '../../Images/clients-logo-04.png'
import client5 from '../../Images/clients-logo-05.png'
import client6 from '../../Images/clients-logo-06.png'
import client7 from '../../Images/clients-logo-07.png'
import client8 from '../../Images/clients-logo-08.png'

export const data = [
    {
        id : 1,
        img : member1,
        name : 'Richard Ford',
        profession : 'Instructor of Mathematics',
        social1 : 'https://www.instagram.com/',
        social2 : 'https://www.linkedin.com/',
        social3 : 'https://dribbble.com/shots',
        social4 : 'https://twitter.com/',
        text : 'Energistically administrate multifunctional rather than front-end expertise.',
        phone : '(+123) 123-456-789',
        email : 'memb1@domain.com',
        text1 : 'Authoritatively deploy fully researched leadership skills whereas one-to-one best practices. Monotonectally aggregate virtual imperatives and accurate technology. Dynamically streamline progressive sources before user friendly.',
        text2 : 'Progressively productize vertical alignments after sticky process improvements. Competently scale transparent methods of empowerment and visionary products.',
        skils : [
            ['Cost', 'Good Business Consultants are Excellent Communicators'],
            ['Corporate', 'At the End of a Project, Good Business Consultants'],
            ['SEO', 'Good Business Consultants are Willing to Travel Where the Work Is'],
            ['Company', 'Write a Business Plan that Clearly Articulates the Following'],
            ['Business', 'Assertively embrace technically sound action'],
            ['Quickly', 'architect customer directed portals with Is'],
            ['Web Agency', 'Synergistically plagiarize robust methodologies'],
        ],
        text3 : 'Holisticly whiteboard low-risk high-yield e-services vis-a-vis user-centric data. Competently benchmark communities whereas interactive.',
        procent1 : '80%',
        procent2 : '70% ',
        procent3 : '85%',
        trusted_by : [client1, client2, client3, client5, client7],
        slug : 'richard_ford',
    },
    {
        id : 2,
        img : member2,
        name : 'Ann Smith',
        profession : 'Finance Lead',
        social1 : 'https://www.instagram.com/',
        social2 : 'https://www.linkedin.com/',
        social3 : 'https://dribbble.com/shots',
        social4 : 'https://twitter.com/',
        text : 'Efficiently deliver business systems through extensible redefine user.',
        phone : '(+123) 123-456-788',
        email : 'memb2@domain.com',
        text1 : 'Authoritatively deploy fully researched leadership skills whereas one-to-one best practices. Monotonectally aggregate virtual imperatives and accurate technology. Dynamically streamline progressive sources before user friendly.',
        text2 : 'Progressively productize vertical alignments after sticky process improvements. Competently scale transparent methods of empowerment and visionary products.',
        skils : [
            ['Corporate', 'At the End of a Project, Good Business Consultants'],
            ['SEO', 'Good Business Consultants are Willing to Travel Where the Work Is'],
            ['Business', 'Assertively embrace technically sound action'],
            ['Quickly', 'architect customer directed portals with Is'],
            ['Web Agency', 'Synergistically plagiarize robust methodologies'],
        ],
        text3 : 'Holisticly whiteboard low-risk high-yield e-services vis-a-vis user-centric data. Competently benchmark communities whereas interactive.',
        procent1 : '30%',
        procent2 : '40%',
        procent3 : '65%',
        trusted_by : [client3, client6, client7],
        slug : 'ann_smith',
    },
    {
        id : 3,
        img : member3,
        name : 'Philip Wilson',
        profession : 'Marketing Head',
        social1 : 'https://www.instagram.com/',
        social2 : 'https://www.linkedin.com/',
        social3 : 'https://dribbble.com/shots',
        social4 : 'https://twitter.com/',
        text : 'Monotonectally mesh customized core competencies through communities.',
        phone : '(+123) 123-456-787',
        email : 'memb3@domain.com',
        text1 : 'Authoritatively deploy fully researched leadership skills whereas one-to-one best practices. Monotonectally aggregate virtual imperatives and accurate technology. Dynamically streamline progressive sources before user friendly.',
        text2 : 'Progressively productize vertical alignments after sticky process improvements. Competently scale transparent methods of empowerment and visionary products.',
        skils : [
            ['Cost', 'Good Business Consultants are Excellent Communicators'],
            ['Corporate', 'At the End of a Project, Good Business Consultants'],
            ['SEO', 'Good Business Consultants are Willing to Travel Where the Work Is'],
            ['Web Agency', 'Synergistically plagiarize robust methodologies'],
        ],
        text3 : 'Holisticly whiteboard low-risk high-yield e-services vis-a-vis user-centric data. Competently benchmark communities whereas interactive.',
        procent1 : '40%',
        procent2 : '50%',
        procent3 : '72%',
        trusted_by : [client1, client2, client3, client5],
        slug : 'philip_wilson',
    },
    {
        id : 4,
        img : member4,
        name : 'Walsh ALex',
        profession : 'Company Director',
        social1 : 'https://www.instagram.com/',
        social2 : 'https://www.linkedin.com/',
        social3 : 'https://dribbble.com/shots',
        social4 : 'https://twitter.com/',
        text : 'Conveniently whiteboard one-to-one bandwidth rather than revolutionary mindshare.',
        phone : '(+123) 123-456-786',
        email : 'memb4@domain.com',
        text1 : 'Authoritatively deploy fully researched leadership skills whereas one-to-one best practices. Monotonectally aggregate virtual imperatives and accurate technology. Dynamically streamline progressive sources before user friendly.',
        text2 : 'Progressively productize vertical alignments after sticky process improvements. Competently scale transparent methods of empowerment and visionary products.',
        skils : [
            ['Cost', 'Good Business Consultants are Excellent Communicators'],
            ['Corporate', 'At the End of a Project, Good Business Consultants'],
            ['SEO', 'Good Business Consultants are Willing to Travel Where the Work Is'],
            ['Company', 'Write a Business Plan that Clearly Articulates the Following'],
            ['Business', 'Assertively embrace technically sound action'],
            ['Quickly', 'architect customer directed portals with Is'],
            ['Web Agency', 'Synergistically plagiarize robust methodologies'],
        ],
        text3 : 'Holisticly whiteboard low-risk high-yield e-services vis-a-vis user-centric data. Competently benchmark communities whereas interactive.',
        procent1 : '90%',
        procent2 : '90%',
        procent3 : '95%',
        trusted_by : [client1, client2, client3, client4, client5, client6, client7, client8],
        slug : 'wash_alex',
    },
    {
        id : 5,
        img : member5,
        name : 'Alan Ford',
        profession : 'Instructor of Mathematics',
        social1 : 'https://www.instagram.com/',
        social2 : 'https://www.linkedin.com/',
        social3 : 'https://dribbble.com/shots',
        social4 : 'https://twitter.com/',
        text : 'Energistically administrate multifunctional rather than front-end expertise.',
        phone : '(+123) 123-456-785',
        email : 'memb5@domain.com',
        text1 : 'Authoritatively deploy fully researched leadership skills whereas one-to-one best practices. Monotonectally aggregate virtual imperatives and accurate technology. Dynamically streamline progressive sources before user friendly.',
        text2 : 'Progressively productize vertical alignments after sticky process improvements. Competently scale transparent methods of empowerment and visionary products.',
        skils : [
            ['Quickly', 'architect customer directed portals with Is'],
            ['Web Agency', 'Synergistically plagiarize robust methodologies'],
        ],
        text3 : 'Holisticly whiteboard low-risk high-yield e-services vis-a-vis user-centric data. Competently benchmark communities whereas interactive.',
        procent1 : '20%',
        procent2 : '42%',
        procent3 : '45%',
        trusted_by : [client1, client3, client7],
        slug : 'alan_ford',
    },
    {
        id : 6,
        img : member6,
        name : 'Nancy ALex',
        profession : 'Product Manager',
        social1 : 'https://www.instagram.com/',
        social2 : 'https://www.linkedin.com/',
        social3 : 'https://dribbble.com/shots',
        social4 : 'https://twitter.com/',
        text : 'Conveniently whiteboard one-to-one bandwidth rather than revolutionary mindshare.',
        phone : '(+123) 123-456-784',
        email : 'memb6@domain.com',
        text1 : 'Authoritatively deploy fully researched leadership skills whereas one-to-one best practices. Monotonectally aggregate virtual imperatives and accurate technology. Dynamically streamline progressive sources before user friendly.',
        text2 : 'Progressively productize vertical alignments after sticky process improvements. Competently scale transparent methods of empowerment and visionary products.',
        skils : [
            ['Corporate', 'At the End of a Project, Good Business Consultants'],
            ['SEO', 'Good Business Consultants are Willing to Travel Where the Work Is'],
            ['Business', 'Assertively embrace technically sound action'],
            ['Quickly', 'architect customer directed portals with Is'],
        ],
        text3 : 'Holisticly whiteboard low-risk high-yield e-services vis-a-vis user-centric data. Competently benchmark communities whereas interactive.',
        procent1 : '70%',
        procent2 : '50%',
        procent3 : '55%',
        trusted_by : [client5, client6, client7],
        slug : 'nancy_alex',
    },
]