export const data = [
    {
        'id' : 1,
        'title' : 'Quick Links',
        'subtitle1' : 'Make Appointment',
        'subtitle2' : 'Department Services',
        'subtitle3' : 'Our Case Studies',
        'subtitle4' : 'Our Business Growth',
        'link1' : '/',
        'link2' : '/',
        'link3' : '/',
        'link4' : '/',
    },
    {
        'id' : 2,
        'title' : 'Company',
        'subtitle1' : 'About Our Services',
        'subtitle2' : 'Our Affiliates Program',
        'subtitle3' : 'View Our Blog',
        'subtitle4' : 'Check Our Careers',
        'link1' : '/',
        'link2' : '/',
        'link3' : '/',
        'link4' : '/',
    },
    {
        'id' : 3,
        'title' : 'LEGAL',
        'subtitle1' : 'Legal Information',
        'subtitle2' : 'Privacy Policy',
        'subtitle3' : 'Report Abuse',
        'subtitle4' : 'Terms of Service',
        'link1' : '/',
        'link2' : '/',
        'link3' : '/',
        'link4' : '/',
    },
    {
        'id' : 4,
        'title' : 'SUPPORT',
        'subtitle1' : 'Contact',
        'subtitle2' : 'Knowledge Base',
        'subtitle3' : 'Forums',
        'subtitle4' : 'System Status',
        'link1' : '/',
        'link2' : '/',
        'link3' : '/',
        'link4' : '/',
    },
]